shintairiku/evaluation-system

- backend/Dockerfile
- backend/app/api/v1/__init__.py
- backend/app/api/v1/auth.py
- backend/app/core/auth.py
- backend/app/core/clerk_config.py
- backend/app/core/exceptions.py
- backend/app/core/permissions.py
- backend/app/dependencies/auth.py
- backend/app/main.py
- backend/app/schemas/auth.py
- backend/app/services/auth_service.py
- backend/requirements.txt
- backend/tests/test_auth.py
- docs/dev/clerk-auth-middleware-implementation.md
- docs/endpoints.md
Implements GitHub issue #13: Backend Clerk Authentication Middleware Setup. Complete authentication middleware with JWT verification, role-based access control, and centralized permission management.
- **JWT Token Verification**: Secure Clerk token validation with real credentials
- **Role-Based Access Control**: 6 roles with 25+ granular permissions
- **FastAPI Dependencies**: Authentication middleware with automatic role checking
- **Centralized Permissions**: Complete permission management system
- **Comprehensive Testing**: 23 test cases (100% pass rate)
- **Docker Ready**: Updated configuration for production deployment
| Endpoint | Method | Status |
|----------|--------|--------|
| `/auth/me` | GET | ✅ Working |
| `/auth/verify` | POST | ✅ Working |
| `/auth/signin` | POST | 501 …
> feat: implement Clerk authentication middleware with centralized permissions

- backend/app/api/v1/__init__.py
- backend/app/api/v1/competencies.py
- backend/app/api/v1/evaluation_periods.py
- backend/app/api/v1/goal_categories.py
- backend/app/api/v1/goals.py
- backend/app/api/v1/self_assessments.py
- backend/app/api/v1/supervisor_feedbacks.py
- backend/app/api/v1/supervisor_reviews.py
- backend/app/schemas/competency.py
- backend/app/schemas/evaluation_period.py
- backend/app/schemas/goal.py
- backend/app/schemas/self_assessment.py
- backend/app/schemas/supervisor_feedback.py
- backend/app/schemas/supervisor_review.py
This pull request implements the domain-based API routing structure for the evaluation system using FastAPI, as specified in Issue #12. It establishes the foundational endpoints for various domains including competencies, evaluation periods, goals, self-assessments, and supervisor reviews.
- Closes #12
- Related to #45 
- **New Routers Added:**
- `competencies`: Manages CRUD for competencies.
- `evaluation_periods`: Manages CRUD for evaluation periods.
- `goal_categories`: Manages CRUD for goal categories.
- `self_assessments`: Manages CRUD for self-assessments.
- `supervisor_feedbacks`: Manages CRUD for supervisor feedbacks.
- `supervisor_reviews`: Manages CRUD for supervisor reviews.
- **Routers Modified:**
- `__init__.py`: Registered all new routers.
- `goals`: Updated to align with …
> feat: Implement `Goals` related API endpoints

- .gitignore
- backend/app/core/CONFIG_MAINTENANCE.md
- backend/app/core/clerk_config.py
- backend/app/core/config.py
- backend/app/database/migrations/018_add_pending_approval_status.sql
- backend/app/database/models/base.py
- backend/app/database/models/user.py
- backend/app/database/repositories/user_repo.py
- backend/app/database/session.py
- backend/app/schemas/auth.py
- backend/app/schemas/profile.py
- backend/app/schemas/user.py
- backend/pytest.ini
- backend/requirements.txt
- backend/tests/repositories/README.md
- backend/tests/repositories/test_logging_utils.py
- backend/tests/repositories/test_user_repo.py
- データベースのレポシトリー層の実装
- 包括的なリポジトリー層のテスト環境とドキュメントのアップロード
- **Centralized Configuration Management** (`backend/app/core/config.py`) with environment-specific settings
- **Clerk Integration Configuration** with simplified direct client usage
- **Database Session Management** with async SQLAlchemy and connection pooling
- **Comprehensive Configuration Documentation** with maintenance guidelines
- **Complete User Model** with department, stage, role, and supervisor relationships
- **Async UserRepository** with comprehensive CRUD operations and filtering capabilities
- **Database Schema Migration** adding `pending_approval` status for user workflow
- **Optimized Enum Handling** using VARCHAR for better flexibility and maintenance
- **Enhanced Auth Schemas** with sign-in request/response and JWT …
> feat: Complete Database Repository and Configuration System for User Authentication

- docs/dev/frontend_api_fetch_guide.md
- frontend/src/api/client/http-client.ts
- frontend/src/api/constants/config.ts
- frontend/src/api/endpoints/auth.ts
- frontend/src/api/endpoints/index.ts
- frontend/src/api/server-actions/auth.ts
- frontend/src/api/server-actions/index.ts
- frontend/src/api/types/auth.ts
- frontend/src/app/page.tsx
- frontend/src/app/profile/confirmation/page.tsx
- frontend/src/app/profile/page.tsx
- frontend/src/components/display/ClerkInfoCard.tsx
- frontend/src/components/display/InactiveAccountMessage.tsx
- frontend/src/components/display/LandingPage.tsx
- frontend/src/components/display/PendingApprovalNotification.tsx
- frontend/src/components/display/UserInfoCard.tsx
- frontend/src/components/display/WelcomeDashboard.tsx
- frontend/src/components/display/index.ts
- frontend/src/components/ui/select.tsx
- frontend/src/feature/profile/confirmation/ConfirmationDisplay.tsx
- frontend/src/feature/profile/display/ProfileForm.tsx
- frontend/src/feature/profile/display/ProfileFormWrapper.tsx
- frontend/src/hooks/useProfileRedirect.ts
- Related to #57 
- Related to #63 
- 
- カスタムバックエンドユーザー管理システムと統合されたフロントエンド認証にClerkを使用した認証およびユーザープロファイル設定システムを実装を完了して。
- 最初の Clerk サインアップからプロファイルの完成、承認ワークフローに至るまで、完全なユーザーオンボーディングフローを提供。
- **Complete Clerk Integration**: Seamless frontend authentication with backend user management
- **User Existence Checking**: Server-side validation of user accounts via Clerk ID
- **Profile Options API**: Dynamic fetching of departments, stages, roles, and existing users for form population
- **Account Status Management**: Support for active, pending approval, and inactive user states
- **Profile Form**: Multi-step profile creation with validation
- **Dynamic Data Loading**: Real-time fetching of organizational data (departments, stages, roles)
- **Supervisor Assignment**: Intelligent supervisor selection …
> feat: Implement Complete Authentication and User Profile Setup System

- backend/app/database/models/user.py
- backend/app/database/repositories/department_repo.py
- backend/app/schemas/department.py
- backend/app/services/user_service.py
- backend/tests/repositories/test_department_repo.py
- backend/tests/test_department_repository.py
- `DepartmentRepository`の実装： CRUD（作成、読み取り、更新、削除）機能、データ検証スキーマが追加
- Department スキーマの定義：サービス・エンドポイント層への下準備
- Closes #50 
-   **Enhanced `DepartmentRepository` (`department_repo.py`)**:
-   Implemented `create_department`, `update_department`, and `delete_department` methods.
-   Added validation to prevent duplicate department names.
-   Included a safeguard to prevent the deletion of departments that have active users.
-   Introduced advanced querying capabilities:
-   `search_departments`: Supports searching by term, filtering, and pagination.
-   `autocomplete_departments`: Provides an efficient, UI-friendly endpoint for real-time suggestions with smart result ordering.
-   `get_department_users`: Retrieves all active users for a given department.
-   **New Department Schemas …
> feat(backend): Implement Department Schemas, Model, and Repository

- backend/app/database/models/user.py
- backend/app/database/repositories/department_repo.py
- backend/app/schemas/department.py
- backend/app/services/department_service.py
- backend/app/services/user_service.py
- backend/tests/repositories/test_department_repo.py
- backend/tests/services/test_department_service.py
- backend/tests/test_department_repository.py
- Departmentサービスレイヤーの実装
- ロールベースアクセスでのCRUDオペレーションの実装
- `backend/app/database/repositories/department_repo.py` - Enhanced filtering capabilities
- `backend/app/schemas/department.py` - Fixed schema types and forward references
- `backend/app/services/department_service.py` - Complete service implementation
- `backend/tests/services/test_department_service.py` - Comprehensive test suite
**Added department_ids filtering support:**
- Enables filtering departments by specific IDs, supporting advanced query capabilities needed by the service layer.
**Fixed forward reference handling:**
- Replaced `PaginatedResponse` with proper `List["User"]` typing
- Implemented safe model rebuilding with error handling
**Transformed from basic service to full business logic layer:**
- **Full CRUD operations** …
> feat(backend): Implement Department Service

- backend/app/api/v1/departments.py
- backend/app/database/models/user.py
- backend/app/database/repositories/department_repo.py
- backend/app/schemas/department.py
- backend/app/services/department_service.py
- backend/app/services/user_service.py
- backend/tests/repositories/test_department_repo.py
- backend/tests/services/test_department_service.py
- backend/tests/test_department_repository.py
- Department APIエンドポイントの実装
- ロールベースアクセス制御によるCRUDオペレーション
- `backend/app/api/v1/departments.py` - Complete CRUD endpoints implementation
**DepartmentService Integration:**
- All endpoints properly delegate to `DepartmentService`
- Leverages established business logic and validation
- Uses `AuthContext` for permission checking
- Maintains consistency with service layer patterns
- ✅ **Service Layer** - All CRUD operations functional
- ✅ **Authentication System** - AuthContext integration complete
- ✅ **Permission System** - Role-based access properly enforced
- ✅ **Error Handling** - Proper exceptions for all error conditions
- ✅ **API Documentation** - Clear docstrings explaining functionality
- ✅ **Code Standards** - Passes ruff linting with no issues
1. **Caching**: Add Redis caching for …
> feat(backend): Implement Department API Endpoints

- .env.local.example
> feat: Add local environment variable example

- backend/app/services/role_service.py
Implement comprehensive RoleService with business logic validation, permission controls, and error handling for role management operations.
Closes #74 - Implement RoleService with business logic
Depends on #73 - Role model and repository
- **Implemented comprehensive RoleService** with full business logic validation
- **Added permission-based access control** using AuthContext integration
- **Implemented role name uniqueness validation** to prevent conflicts
- **Added system role protection** (prevents deletion of admin/supervisor/employee roles)
- **Created comprehensive error handling** with custom exceptions
- **Added transaction management** with automatic rollback on errors
- **Implemented audit logging** for all role operations
- **Added data enrichment methods** for response …
> 74 role service

- backend/app/database/models/user.py
- backend/app/database/repositories/competency_repo.py
Implementation of the competency domain data layer including SQLAlchemy model and repository pattern for managing competency entities in the HR evaluation system.
Closes #103
- Add `Competency` SQLAlchemy model with UUID primary key, name, description, and timestamps
- Implement bidirectional relationship between `Competency` and `Stage` models
- Create `CompetencyRepository` following the established repository pattern
- Add comprehensive CRUD operations: create, get_by_id, get_all, update, delete
- Implement stage-based filtering with `get_competencies_by_stage()` method
- Add search functionality with `search_competencies()` method supporting name and description
- Include proper error handling and logging throughout the repository
- Follow established naming conventions and code …
> feat(backend): implement Competency model and repository for task #103

- docs/requirement-definition/02-tech/architecture/02-fe-architecture.md
- frontend/src/api/README.md
- frontend/src/api/endpoints/README.md
- frontend/src/components/auth/AuthRedirectHandler.tsx
- frontend/src/feature/profile/display/ProfileForm.tsx
- frontend/src/feature/profile/display/ProfileFormWrapper.tsx
- フロントエンドAPI統合レイヤーのリファクタリング
- **サーバーファースト**アーキテクチャを採用
- React 19の`useActionState`とNext.js Server Actionsを活用
- これらの変更により、SSRとクライアントコンポーネントの両方でAPIの使用可能となり、型安全性が向上し、エラーと読み込み状態の処理が統一
- この変更にて、`frontend/src/api/endpoints/...`にて定義されたファイルは使用せず、`frontend/src/api/server-actions/....`のみでサーバーサイドとクライアントサイドの両方のレンダリング手法にも対応可能。
- 詳しい使い方は、以下のドキュメントを参照:
- [Overall Frontend Guide](https://github.com/shintairiku/evaluation-system/blob/refactor/user-profile-setup/docs/requirement-definition/02-tech/architecture/02-fe-architecture.md)
- [How To Set Up Frontend API Layer](https://github.com/shintairiku/evaluation-system/blob/refactor/user-profile-setup/frontend/src/api/README.md)
- 参考記事: 
- https://zenn.dev/akfm/books/nextjs-basic-principle/viewer/part_1_interactive_fetch
- …
> refactor: Frontend API Layer to Server-First Architecture with useActionState

- frontend/src/api/types/auth.ts
- frontend/src/components/display/UserInfoCard.tsx
- frontend/src/components/display/WelcomeDashboard.tsx
- frontend/src/components/display/index.ts
- frontend/src/feature/evaluation/admin/report/display/index.tsx
- frontend/src/feature/user-profiles/display/FilterBar.tsx
- frontend/src/feature/user-profiles/display/UserEditViewModal.tsx
- frontend/src/feature/user-profiles/display/UserTableView.tsx
- frontend/src/feature/user-profiles/display/index.tsx
- frontend/src/hooks/useLoading.ts
⏺ Summary
Implements task #115 by connecting department, stage, and role filter dropdowns in the User Management page to real backend data using Server Actions. Replaces static dropdown options with dynamic data fetched from the API, adds loading states, error handling, and functional filtering capabilities.
Related Issues
Closes #115
Type of Change
Changes Made
- `FilterBar.tsx`: Connected department, stage, and role dropdowns to backend via `getProfileOptionsAction()` Server Action
- `FilterBar.tsx`: Added loading states with "読み込み中..." placeholders during data fetching
- `FilterBar.tsx`: Implemented error handling with Japanese toast notifications for API failures
- `FilterBar.tsx`: Added functional filter state management with `onFilter` callback
- `FilterBar.tsx`: Fixed `SelectItem` …
> 115 pageuser manage connect departmentrole dropdowns

- backend/app/api/v1/users.py
- backend/app/services/user_service.py
- frontend/package-lock.json
- frontend/package.json
- frontend/src/feature/user-profiles/display/UserManagementWithSearch.tsx
- frontend/src/feature/user-profiles/display/UserOrganizationView.tsx
Closes #145
- Added React Flow integration for interactive organizational chart visualization  
- Implemented hierarchical user layout algorithm with proper parent-child relationships  
- Fixed duplicate user count display by conditionally hiding redundant count in organization view  
- Enhanced user cards with comprehensive information display (name, role, department, status, email)  
- Added visual styling with role-based color coding and status badges  
- Improved navigation controls with zoom, pan, and reset functionality  
- Added responsive design for better viewing across different screen sizes  
- Implemented proper spacing and alignment to prevent node overlapping  
- The organizational chart view provides an intuitive way to visualize user hierarchies and reporting relationships …
> 145 react flow organization view v2

- backend/app/api/v1/self_assessments.py
- backend/app/database/models/__init__.py
- backend/app/database/models/evaluation.py
- backend/app/database/models/goal.py
- backend/app/database/models/self_assessment.py
- backend/app/database/repositories/self_assessment_repo.py
- backend/app/schemas/goal.py
- backend/app/schemas/self_assessment.py
- backend/app/schemas/supervisor_review.py
- backend/app/security/permissions.py
- backend/app/services/self_assessment_service.py
Comprehensive implementation of the **Self Assessments API** (Phase **3A** — Self Assessment Process).  
Enables employees to create, update, and submit self-evaluations for their goals with proper RBAC and validation.
- Closes **#134**
- **Database Model**
- Added `SelfAssessment` with relationships to `Goal` and `EvaluationPeriod`
- Fields: self-rating (0–100), self-comment, status tracking, submission timestamps
- **Repository Layer**
- Implemented `SelfAssessmentRepository` with full CRUD
- Filtering by period/user/status and goal-specific queries
- **Service Layer**
- Added `SelfAssessmentService` with business logic for lifecycle management
- RBAC enforcement, status validation, and goal relationship management
- **API Endpoints**
- Complete REST API: list, create, update, submit, …
> 134 implement self assessments api phase 3a

- backend/app/database/repositories/goal_repo.py
- backend/app/services/goal_service.py
- 目標アップデートの際の検証ロジック修正
- 目標レポジトリーにコンディショナルベースのデータ処理を実装
> Fix: Implement Goal Repository for Conditional Data Handling

- .kiro/specs/custom-jwt/design.md
- .kiro/specs/custom-jwt/requirements.md
- .kiro/specs/custom-jwt/tasks.md
- backend/app/database/migrations/029_create_organizations.sql
- backend/app/database/models/__init__.py
- backend/app/database/models/organization.py
- backend/app/database/models/user.py
- backend/app/schemas/auth.py
- backend/app/services/auth_service.py
- frontend/src/api/types/clerk.ts
- frontend/src/api/types/index.ts
Implements Feature A (Clerk Settings and Metadata Management) from the custom JWT token enhancement project. This PR establishes the foundational database schema and TypeScript type definitions required for Clerk organization integration and multi-tenant functionality.
Part of custom JWT token enhancement with organization support implementation.
- **Created ** with comprehensive type definitions:
- `ClerkPublicMetadata` and `ClerkPrivateMetadata` interfaces
- `JWTClaims` interface matching Clerk JWT template structure
- `Organization` and related CRUD interfaces
- `DomainSettings` for domain-based auto-approval functionality
- Webhook payload types for all supported Clerk events
- `OrganizationMember` and membership-related interfaces
- **Updated `/frontend/src/api/types/index.ts`** to …
> feat(custom-jwt): implement Clerk organization database schema and TypeScript types

- frontend/src/api/types/clerk.ts
- Remove `email` fields from the custom JWT token
> fix: Update Custom JWT Token

- .kiro/specs/custom-jwt/tasks.md
- backend/app/api/v1/__init__.py
- backend/app/api/v1/admin.py
- backend/app/api/v1/users.py
- backend/app/main.py
- backend/app/security/dependencies.py
- backend/app/security/rbac_helper.py
- backend/app/services/competency_service.py
- backend/app/services/evaluation_period_service.py
- backend/app/services/goal_service.py
- backend/app/services/role_service.py
- backend/app/services/self_assessment_service.py
- backend/app/services/supervisor_feedback_service.py
- backend/app/services/supervisor_review_service.py
- backend/app/services/user_service.py
- Enhance RBAC helper to support organization-scoped subordinate user retrieval 
- Add improved JWT token-derived role fallback functionality for better cross-organization access control
- Update implementation plan documentation to reflect actual development progress and design changes
- **Organization-scoped subordinate retrieval**: Update `RBACHelper._get_subordinate_user_ids()` to require `org_id` parameter for proper organizational scoping
- **Enhanced cache keys**: Include organization ID in subordinate cache keys to prevent cross-organizational data leaks
- **JWT role derivation**: Improve fallback mechanism when users have valid tokens but limited database roles
- **Improved logging**: Add detailed logging for cross-organization access patterns while protecting sensitive token …
> feat(rbac): add organization scope to subordinate user retrieval and enhance logging for cross-organization access

- backend/app/services/user_service.py
- frontend/src/api/types/clerk.ts
- frontend/src/api/utils/jwt-parser.ts
- frontend/src/feature/setup/display/ProfileForm.tsx
This PR refactors the signup profile system to support multiple user roles, replacing the previous single-role limitation with a more flexible multi-role architecture. The changes enhance both backend user creation and frontend role selection interfaces.
- **Role Arrays**: Replaced single `role` field with `roles` array in Clerk metadata and JWT tokens
- **Enhanced Metadata**: User creation now stores all assigned role names in Clerk public metadata
- **Flexible Context**: JWT tokens now carry complete role information for authorization
- **Admin Role Filtering**: Admin role is now hidden from user selection during signup process
- **Better Role Display**: Users can select multiple roles with improved visual feedback
- **Enhanced Validation**: Role selection provides clearer feedback and …
> feat: Refactor signup profile to support multiple user roles

- backend/app/api/v1/goals.py
- backend/app/database/models/goal.py
- backend/app/database/repositories/goal_repo.py
- backend/app/database/repositories/supervisor_review_repository.py
- backend/app/schemas/goal.py
- backend/app/services/goal_service.py
- backend/app/services/supervisor_review_service.py
- frontend/src/api/endpoints/goals.ts
- frontend/src/api/server-actions/goals.ts
- frontend/src/api/types/goal.ts
- frontend/src/feature/goal-input/display/ConfirmationStep.tsx
- frontend/src/hooks/useGoalAutoSave.ts
- frontend/src/hooks/useGoalData.ts
- frontend/src/hooks/useGoalTracking.ts
- frontend/src/hooks/usePeriodSelection.ts
This PR refactors the goal status workflow from `incomplete` → `pending_approval` to `draft` → `submitted`, implementing comprehensive auto-save functionality for better user experience and data persistence.
None specified
1. **Status Schema Updates** (`backend/app/schemas/goal.py`, `backend/app/database/models/goal.py`)
- Removed `INCOMPLETE` status enum value
- Renamed `PENDING_APPROVAL` to `SUBMITTED`
- Updated default status from `incomplete` to `draft`
- Updated database constraints and validation
2. **API Updates** (`backend/app/api/v1/goals.py`)
- Updated status query parameters to use `submitted` instead of `pending_approval`
- Updated submit endpoint documentation
3. **Repository Layer** (`backend/app/database/repositories/goal_repo.py`)
- Updated status transitions and …
> Fix: Refactor goal status workflow and implement comprehensive auto-save functionality

- .kiro/specs/evaluation-period-management/tasks.md
- frontend/src/api/client/http-unified-client.ts
- frontend/src/api/constants/config.ts
- frontend/src/api/endpoints/evaluation-periods.ts
- frontend/src/api/server-actions/evaluation-periods.ts
- frontend/src/api/types/evaluation-period.ts
- frontend/src/app/(evaluation)/(admin)/evaluation-period-management/page.tsx
- frontend/src/components/constants/routes.ts
- frontend/src/components/display/sidebar.tsx
- frontend/src/components/ui/side-panel.tsx
- frontend/src/feature/evaluation-period-management/EvaluationPeriodManagementContainer.tsx
- frontend/src/feature/evaluation-period-management/EvaluationPeriodManagementView.tsx
- frontend/src/feature/evaluation-period-management/components/CreateEditPeriodModal.tsx
- frontend/src/feature/evaluation-period-management/components/DeleteConfirmationModal.tsx
- frontend/src/feature/evaluation-period-management/components/EvaluationPeriodCalendarView.tsx
- frontend/src/feature/evaluation-period-management/components/EvaluationPeriodListView.tsx
- frontend/src/feature/evaluation-period-management/components/EvaluationPeriodManagementHeader.tsx
- frontend/src/feature/evaluation-period-management/components/GoalStatisticsSidePanel.tsx
- frontend/src/feature/evaluation-period-management/components/PeriodCard.tsx
- frontend/src/feature/evaluation-period-management/index.ts
- frontend/src/feature/evaluation-period-management/types.ts
- frontend/src/feature/goal-input/display/CompetencyGoalsStep.tsx
- frontend/src/lib/evaluation-period-utils.ts
- frontend/src/lib/evaluation-period-validation.ts
HR評価システムで評価期間を管理するためのUI実装
- Added dedicated route for evaluation period management
- Integrated Calendar icon in sidebar navigation
- Implemented admin-only access control
- Created server-side page component with server actions
- Developed responsive and accessible management interface
- Implemented two primary views: List and Calendar
- Created modular components for complex interactions
- `CreateEditPeriodModal`
- `DeleteConfirmationModal`
- `EvaluationPeriodListView`
- `EvaluationPeriodCalendarView`
- `GoalStatisticsSidePanel`
- Implemented client-side container with comprehensive state handling
- Added optimistic UI updates for better user experience
- Integrated server actions for data mutations
- Implemented error handling and loading states
- Enhanced type definitions in …
> Feat: Advanced Evaluation Period Management UI with Comprehensive Features

- .kiro/specs/home-page/tasks.md
- frontend/src/api/endpoints/index.ts
- frontend/src/api/endpoints/supervisor-dashboard.ts
- frontend/src/api/server-actions/index.ts
- frontend/src/api/server-actions/supervisor-dashboard.ts
- frontend/src/api/types/index.ts
- frontend/src/api/types/supervisor-dashboard.ts
- frontend/src/components/dashboard/index.ts
- frontend/src/components/dashboard/supervisor/SubordinatesCard.tsx
- frontend/src/components/dashboard/supervisor/SupervisorActionsCard.tsx
- frontend/src/components/dashboard/supervisor/SupervisorDashboard.tsx
- frontend/src/components/dashboard/supervisor/SupervisorPendingApprovalsCard.tsx
- frontend/src/components/dashboard/supervisor/TeamProgressCard.tsx
- frontend/src/components/dashboard/supervisor/index.ts
This pull request implements a comprehensive Supervisor Dashboard components, providing supervisors with a centralized view of their team's performance, pending tasks, and quick actions.
- **Team Progress Dashboard**: Visualize team evaluation progress with detailed metrics
- **Pending Approvals Card**: Track goal and feedback approval tasks
- **Subordinates List**: Manage and monitor team members' evaluation status
- **Quick Actions Card**: Fast access to key supervisor functions
- Created comprehensive TypeScript types in `frontend/src/api/types/supervisor-dashboard.ts`
- Defined interfaces for:
- `TeamProgressData`
- `SupervisorPendingApprovalsData`
- `SubordinatesListData`
- `SupervisorDashboardData`
- Implemented API endpoints in `frontend/src/api/endpoints/supervisor-dashboard.ts`
- …
> feat(dashboard): Implement Comprehensive Supervisor Dashboard

- backend/app/api/v1/supervisor_reviews.py
- backend/app/database/migrations/production/006_add_subordinate_id_to_supervisor_reviews.sql
- backend/app/database/models/supervisor_review.py
- backend/app/database/repositories/supervisor_review_repository.py
- backend/app/services/goal_service.py
- backend/app/services/supervisor_review_service.py
- frontend/src/api/constants/config.ts
- frontend/src/api/endpoints/supervisor-reviews.ts
- frontend/src/api/server-actions/supervisor-reviews.ts
Refactor the supervisor review system to align with practical workflow requirements by:
- Adding direct subordinate filtering capabilities
- Removing redundant API endpoints and server actions
- Streamlining the codebase for better maintainability
- Added `subordinate_id` column to `supervisor_reviews` table with migration script
- Updated `SupervisorReview` model to include `subordinate_id` field
- Added `subordinate_id` filtering to all repository query methods:
- `get_by_supervisor()`, `count_by_supervisor()`
- `get_pending_reviews()`
- `search()`, `count_all()`
- Enhanced main endpoint `GET /supervisor-reviews/` with `subordinateId` query parameter
- Enhanced pending reviews endpoint `GET /supervisor-reviews/pending` with `subordinateId` parameter
- **Removed redundant endpoints**: …
> Refactor supervisor review system with subordinate filtering and code cleanup

- .kiro/specs/goal-review-ui/tasks.md
- .kiro/specs/home-page/tasks.md
- backend/app/api/v1/__init__.py
- backend/app/api/v1/dashboard.py
- backend/app/database/models/supervisor_review.py
- backend/app/schemas/dashboard.py
- backend/app/services/dashboard_service.py
- docs/performance-optimization-plan.md
- frontend/src/app/layout.tsx
- frontend/src/components/display/sidebar.tsx
- frontend/src/components/ui/loading-skeleton.tsx
- frontend/src/context/GoalReviewContext.tsx
- frontend/src/feature/evaluation/superviser/goal-review/components/ActionButtons/index.tsx
- frontend/src/feature/evaluation/superviser/goal-review/components/ApprovalForm/index.tsx
- frontend/src/feature/evaluation/superviser/goal-review/components/ApprovalGuidelinesPanel/index.tsx
- frontend/src/feature/evaluation/superviser/goal-review/components/ConfirmationDialog/index.tsx
- frontend/src/feature/evaluation/superviser/goal-review/components/ErrorBoundary/index.tsx
- frontend/src/feature/evaluation/superviser/goal-review/components/GoalApprovalCard/index.tsx
- frontend/src/feature/evaluation/superviser/goal-review/components/GoalApprovalHandler/index.tsx
- frontend/src/feature/evaluation/superviser/goal-review/components/GuidelinesAlert/index.tsx
- frontend/src/feature/evaluation/superviser/goal-review/display/index.tsx
- frontend/src/feature/evaluation/superviser/goal-review/hooks/useCompetencyNames.ts
- frontend/src/feature/evaluation/superviser/goal-review/hooks/useGoalReviewData.ts
- frontend/src/feature/evaluation/superviser/goal-review/hooks/useIdealActionsResolver.ts
管理者、スーパーバイザー、従業員向けのダッシュボードにて使用するAPIエンドポイントの実装
- **System Statistics**: Track users, departments, evaluation periods, goals, and evaluations across the organization
- **Pending Approvals**: Monitor pending user registrations, goal submissions, and evaluation reviews
- **System Alerts**: Automatic deadline warnings and critical notifications with severity levels
- **Granular Endpoints**: Separate endpoints for stats, approvals, and alerts for flexible frontend integration
- **Team Progress**: Track subordinate completion rates across goal setting, self-assessments, and feedback
- **Pending Tasks**: View goal approvals and feedback submissions requiring attention, including overdue items
- **Subordinate Management**: Detailed status for each team member with priority-based task lists
- …
> feat(Dashboard-E) implement dashboard endpoints with role-based access control

- .github/workflows/deploy-backend.yml
- .gitignore
- docs/deployment.md
Implement robust CI/CD pipeline for backend deployment on Google Cloud Run, with support for both production and development environments
- Created automated GitHub Actions workflow for backend deployment
- Implemented environment-specific deployment configurations
- Added secret management for different deployment stages
- Enhanced `.gitignore` to prevent sensitive file leaks
- Added `.github/workflows/deploy-backend.yml` for automated deployments
- Updated `.gitignore` to exclude GCP service account keys
- Extended `docs/deployment.md` with detailed deployment instructions
- Configured separate deployment flows for production and development
- Automatic Docker image building and pushing
- Environment-specific secret management
- Flexible scaling (0-10 instances)
- Configurable memory …
> Feat: Backend Deployment CI/CD Pipeline for Cloud Run

- backend/app/core/middleware.py
- backend/app/security/dependencies.py
This PR addresses critical networking and authentication challenges that impact both Cloud Run deployment and local Docker environments, focusing on middleware, request validation, and debugging enhancements.
1. **Cloud Run Health Check Issues**: Previous middleware configuration prevented proper health checks
2. **Inconsistent Authorization Header Handling**: Strict case-sensitive authentication checks
3. **Limited Debugging for Organization Validation**: Insufficient logging for troubleshooting access problems
- Added explicit public route exemptions for:
- Root paths (`/`, `/health`)
- Documentation endpoints (`/docs`, `/redoc`)
- Authentication and webhook routes
- Enhanced CORS and OPTIONS request handling
- Made header parsing case-insensitive to support various proxy configurations …
> Fix: Network & Authorization Middleware Robustness
